language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
# Disabling Torque setup until we can get this working on Travis
# before_install:
#     - sudo apt-get install torque-server torque-client torque-mom torque-pam
#     - sudo ./test/setup_torque.sh
install:
    - pip install .
before_script:
    - pip install -r test/requirements_test.txt
script:
    - payu list
    - pylint --extension-pkg-whitelist=netCDF4 -E payu
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 ]]; then PYTHONPATH=. pytest --cov=payu -s test; fi;
    - cd docs && make html
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coveralls; fi;
