language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
# Disabling Torque setup until we can get this working on Travis
#before_install:
#    - sudo apt-get install torque-server torque-client torque-mom torque-pam
#    - sudo ./test/setup_torque.sh
install:
    - pip install .
before_script:
    - pip install -r test/requirements_test.txt
script:
    - PYTHONPATH=$(pwd) coverage run --source payu bin/payu
after_success:
    - coverage report -m
    - coveralls
